name: Chrome

on: push

jobs:
    chrome:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Cypress install
              uses: cypress-io/github-action@v2
              timeout-minutes: 10
            -name: Test
              with:
                  start: npm test ./cypress/integration/swag-labs-login.js
                  browser: chrome
