name: Chrome

on: push

jobs:
    chrome:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Cypress install
              uses: cypress-io/github-action@v2
            - name: Test Run
              timeout-minutes: 10
              with:
                  start: npm start
                  browser: chrome
