name: E2E tests

on:
    push:
        path-ignore:
            - '**/js'
            - '**/js'

jobs:
    chrome:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Save build folder
              uses: actions/upload-artifact@v2
              with:
                  name: build
                  if-no-files-found: error
                  path: build

            - name: Cypress install
              uses: cypress-io/github-action@v2
              timeout-minutes: 10
              with:
                  spec: cypress/integration/tests/*
                  start: npm test
                  browser: chrome
