name: Chrome

on:
    push:
        path-ignore:
            - '**/1-getting-started.js'
            - '.**/2-advanced-examples.js'

jobs:
    chrome:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1
            - name: Cypress install
              uses: cypress-io/github-action@v2
              timeout-minutes: 10
              with:
                  start: npm test
                  browser: chrome
